[project]
name = "simplechat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bottle>=0.13.4",
    "docker>=7.1.0",
    "mariadb>=1.1.13",
]
